inherit_from: .rubocop_todo.yml

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 132
  Exclude:
    - 'config/schedule.rb'

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 500

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 65

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Lint/UselessAssignment:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - 'bin/*'
    - 'config/environments/*.rb'
    - 'config/*.rb'
    - 'spec/*.rb'

Style/BlockComments:
  Exclude:
    - 'spec/*.rb'

Style/AlignParameters:
  Exclude:
    - 'bin/*'
